image: registry.gitlab.com/jinay1991/motion_planning

bazel-build:
  stage: build
  script:
    - bazel build //...

bazel-test:
  stage: test
  dependencies:
    - bazel-build
  script:
    - bazel test //... --test_output=all --cache_test_results=false --test_arg="--gtest_output=xml:/tmp/test_results.xml"
  artifacts:
    reports:
      junit: /tmp/test_results.xml
    name: test results
    when: on_success

code-coverage:
  stage: test
  script:
    - bazel test //... --test_output=all --cache_test_results=false --collect_code_coverage=true
  after_script:
    - export OUTPUT_DIR=$(bazel info execution_root)
    - export COVERAGE_INFO=$(find $OUTPUT_DIR -name coverage.dat)
    - genhtml -s --num-spaces 4 --legend --highlight --sort -t "Test Coverage" --demangle-cpp --function-coverage --branch-coverage -o coverage $COVERAGE_INFO
  coverage: /^functions.*\s+(\d+\%)$/
  artifacts:
    paths:
      - coverage
    name: code-coverage
    when: on_success

pages:
  stage: deploy
  dependencies:
    - code-coverage
  script:
    - mv coverage/ public
  artifacts:
    paths:
      - public
    expire_in: 30 days
