image: registry.gitlab.com/jinay1991/motion_planning

bazel-build-and-test:
  stage: build
  script:
    - bazel build //...
  after_script:
    - bazel test //:motion_planning_tests --test_output=all --cache_test_results=false --test_arg="--gtest_output=xml:/tmp/test_results.xml"
    - cp /tmp/test_results.xml test_results.xml
  artifacts:
    reports:
      junit: test_results.xml
    name: TestResults
    when: on_success

code-coverage:
  stage: test
  script:
    - bazel test //... --test_output=all --cache_test_results=false --collect_code_coverage=true
    - export OUTPUT_DIR=$(bazel info execution_root)
    - export COVERAGE_INFO=$(find $OUTPUT_DIR -name coverage.dat)
    - genhtml -s --num-spaces 4 --legend --highlight --sort -t "Test Coverage" --demangle-cpp --function-coverage --branch-coverage -o coverage $COVERAGE_INFO
  coverage: /functions.*:\s(\d+.\d+%)/
  artifacts:
    paths:
      - coverage/
    name: code-coverage
    when: on_success
    expire_in: 1 day

pages:
  stage: deploy
  dependencies:
    - code-coverage
  script:
    - mv coverage/ public
  artifacts:
    paths:
      - public
    expire_in: 30 days

docker-build:
  script:
    - docker build -t registry.gitlab.com/jinay1991/motion_planning .
    - docker push registry.gitlab.com/jinay1991/motion_planning
  only:
    changes:
      - Dockerfile
      - schedules
