image: registry.gitlab.com/jinay1991/motion_planning

before_script:
  - bundle install

build:
  stage: build
  script:
    - bazel build //...

test:
  stage: test
  script:
    - bazel test //... --test_output=all --cache_test_results=false

coverage:
  stage: deploy
  script:
    - bundle exec bazel test //... --test_output=all --cache_test_results=false --collect_code_coverage=true --test_arg="--gtest_output=xml:test_results.xml" -d test_results
    - export OUTPUT_DIR=$(bazel info execution_root)
    - export COVERAGE_INFO=$(find $OUTPUT_DIR -name coverage.dat)
    - bundle exec genhtml -s --num-spaces 4 --legend --highlight --sort -t "Motion Planning" --demangle-cpp --function-coverage --branch-coverage $COVERAGE_INFO -o coverage -d coverage_bundle
    - tar czvf coverage.tar.gz coverage/
  artifacts:
    paths:
      - coverage_bundle
    reports:
      junit: test_results
    when: on_success

package:
  stage: deploy
  script:
    - echo "Generate Package"
